# Generated by Django 4.2 on 2023-05-04 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_comment.category')),
            ],
        ),
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.ImageField(upload_to='images/')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtube_comment.category')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('thumbnail_url', models.URLField()),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('count_of_view', models.PositiveBigIntegerField(default=0)),
                ('count_of_comment', models.PositiveBigIntegerField(default=0)),
                ('categories', models.ManyToManyField(through='youtube_comment.Trending', to='youtube_comment.category')),
            ],
        ),
        migrations.AddField(
            model_name='trending',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_comment.video'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_comment.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_comment.video')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='videos',
            field=models.ManyToManyField(through='youtube_comment.Trending', to='youtube_comment.video'),
        ),
    ]
